version: '3.1'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pasword
      POSTGRES_DB: db
    ports:
      - "5432:5432"