version: '3.8'

services:
  db:
    image: ankane/pgvector:latest
    env_file:
    - .env.docker
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data  # Use a named volume for data persistence

  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
    - .env.docker
    environment:
      - PYTHONPATH=/app
    depends_on:
      - db
    volumes:
      - .:/app
      - /data:/data

volumes:
  pgdata: