"""Remove documents model

Revision ID: f5c0b8fff466
Revises: cbf36d676b77
Create Date: 2025-01-04 20:15:53.491237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5c0b8fff466'
down_revision: Union[str, None] = 'cbf36d676b77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chunks_document_id_fkey', 'chunks', type_='foreignkey')
    op.drop_column('chunks', 'document_id')
    op.drop_index('ix_documents_id', table_name='documents')
    op.drop_table('documents')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'chunks',
        sa.Column(
            'document_id',
            sa.INTEGER(),
            autoincrement=False,
            nullable=False))
    op.create_foreign_key(
        'chunks_document_id_fkey',
        'chunks',
        'documents',
        ['document_id'],
        ['id'])
    op.create_table('documents',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='documents_user_id_fkey'),
                    sa.PrimaryKeyConstraint('id', name='documents_pkey')
                    )
    op.create_index('ix_documents_id', 'documents', ['id'], unique=False)
    # ### end Alembic commands ###
