"""Map document columns

Revision ID: 07100eaf9234
Revises: c2efe3c1588e
Create Date: 2025-01-13 21:05:33.872061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07100eaf9234'
down_revision: Union[str, None] = 'c2efe3c1588e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('documents', 'uuid',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_unique_constraint(None, 'documents', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='unique')
    op.alter_column('documents', 'uuid',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('documents', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
