"""Add document

Revision ID: c2efe3c1588e
Revises: 393259039e42
Create Date: 2025-01-12 22:48:47.449457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2efe3c1588e'
down_revision: Union[str, None] = '393259039e42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('chunks', sa.Integer(), nullable=True),
                    sa.Column('uuid', sa.UUID(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('id')
                    )
    op.create_index(op.f('ix_documents_name'),
                    'documents', ['name'], unique=False)
    op.create_index(op.f('ix_documents_uuid'),
                    'documents', ['uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upsertion_record',
                    sa.Column('uuid', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('key', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.Column('namespace', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('group_id', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.Column('updated_at', sa.DOUBLE_PRECISION(
                        precision=53), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint(
                        'uuid', name='upsertion_record_pkey'),
                    sa.UniqueConstraint('key', 'namespace',
                                        name='uix_key_namespace')
                    )
    op.create_index('ix_upsertion_record_uuid',
                    'upsertion_record', ['uuid'], unique=False)
    op.create_index('ix_upsertion_record_updated_at',
                    'upsertion_record', ['updated_at'], unique=False)
    op.create_index('ix_upsertion_record_namespace',
                    'upsertion_record', ['namespace'], unique=False)
    op.create_index('ix_upsertion_record_key',
                    'upsertion_record', ['key'], unique=False)
    op.create_index('ix_upsertion_record_group_id',
                    'upsertion_record', ['group_id'], unique=False)
    op.create_index('ix_key_namespace', 'upsertion_record',
                    ['key', 'namespace'], unique=False)
    op.drop_index(op.f('ix_documents_uuid'), table_name='documents')
    op.drop_index(op.f('ix_documents_name'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
